version: '3'

services:

  temperature:
    image: pluspeterpublic/temperature:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  windspeed:
    image: pluspeterpublic/windspeed:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped

  weather:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - temperature
      - windspeed
    restart: unless-stopped
    tty: true


